// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWU0vzZry6dImJXKZw2aazrM7gqoe-Pw',
    appId: '1:631801115194:web:9edacd30604d2a2a15bb03',
    messagingSenderId: '631801115194',
    projectId: 'anime-a7e60',
    authDomain: 'anime-a7e60.firebaseapp.com',
    storageBucket: 'anime-a7e60.appspot.com',
    measurementId: 'G-C4T59HL5TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6K_pnwt6lANcctcOSvzGCai1sN3zH3g',
    appId: '1:631801115194:android:5802a26914411d5a15bb03',
    messagingSenderId: '631801115194',
    projectId: 'anime-a7e60',
    storageBucket: 'anime-a7e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBaQv0R9fnXFqsW66ceYantWHA-pyvFc',
    appId: '1:631801115194:ios:bdf0dfe3c5781cc415bb03',
    messagingSenderId: '631801115194',
    projectId: 'anime-a7e60',
    storageBucket: 'anime-a7e60.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNBaQv0R9fnXFqsW66ceYantWHA-pyvFc',
    appId: '1:631801115194:ios:bdf0dfe3c5781cc415bb03',
    messagingSenderId: '631801115194',
    projectId: 'anime-a7e60',
    storageBucket: 'anime-a7e60.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
